---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: demo-keycloak-instance
  namespace: demo-project
  labels:
    app: sso
spec:
  http:
    httpEnabled: true
    httpPort: 8090
    tlsSecret: my-tls-secret
  hostname:
    adminUrl: 'https://keycloak-rhdh-operator.apps.cluster-db131a98-9636-4a3d-a6a2-2d2e6482e986.apps.ocp-knowitno.cncs.dk'
    hostname: keycloak-rhdh-operator.apps.cluster-db131a98-9636-4a3d-a6a2-2d2e6482e986.apps.ocp-knowitno.cncs.dk
  instances: 1
  db:
    vendor: postgres
    host: keycloak-postgres
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
...
