---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
  namespace: demo-project
  labels:
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  BACKEND_SECRET: N4KQcvTEIi6lAMGB5S0vHvBZdeAh789+J
  K8S_SA_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6ImZHei1xXzZCWTZNQ2hwNGp1cU1iaEdkOFh2M2pPLXFsQVpSZDVpS1kzNDAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZW1vLXByb2plY3QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoicmhkaC1rOHMtc2EtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoicmhkaC1rOHMtc2EiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIxMThmNWFmMy1mMzQwLTQzNmUtOTZiOS1iOTk3NmI4Mjk3MzQiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVtby1wcm9qZWN0OnJoZGgtazhzLXNhIn0.tj78JqfyAkw2Fo_Mzm7NInINrcalpy-JGc2uCekoh0aNhwPP0PKjp-5Y4tnBSbAd44kuBvNgiJhlW9yaUofAZ6VoR7ClrLs3rzOsxI8FPOSGDP8h3S2TpOE9RcgJjil870hPKpBeDQSaJnjsqdI2j6t-o2VjUhKtj-zHo4WMGiJl7CSqzygSOlMrjTvdlo8GjfiZQmivFwO0GoBzMNzYoaNwjx-Hz0s9qkvfQ1jTUu5IuduGj6eESHO0b8fnBLxCBaGqcCNI2e60Fzs-vaPZtH75MvXM9LR8VxWpB9Vy7Wbnklk37FQGjBWsL3LDk1nOe5YUfbHLjZCi-FgbRQSKEVipZdwW2CKSrGw3gmdvUb8UbX-qnrV8yL4H9M-rwfZ1_lWdO1E3E4Hw35z16t7rWK8yqknRNU_R5biIqWGXA8LRagNjIOBaCby3R9UGXAISn7HQzm5XF7LPBsRuxzlg1W8WmFUIXviOPQqQapOnQaOAOeW7dlHsIXyJL9N7LjRzmrDk0p7St-RZ11qHvtTR2nrgLYQAoJnMQt2H6WRLMk2jodcID5vqKb9A3Skzgk6kph6R2oDDGZaA3TVZVSZdqTS12xgkNxSch3RhPRKnMKcqpx8SA5yYZWM6rZeAyXEIbqKKXjen8tcKj4DXj6SyAL6xLp85m9_2taG0dtmlH9k
  GITHUB_TOKEN: <placeholder>
